language: r
warnings_are_errors: false
cache: packages
sudo: false
r_packages:
- curl
- jsonlite
- leafletR
r_github_packages: rladies/meetupr
after_failure:
- cat rcommunityexplorer.Rcheck/00install.out
after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash
  deploy.sh
before_install:
- openssl aes-256-cbc -K $encrypted_03d543abc5e6_key -iv $encrypted_03d543abc5e6_iv
  -in R/.httr-oauth.enc -out R/.httr-oauth -d
